### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by enterprisey** [jacobswain/markdown-tutorial#1]
At the moment, there's no real sense of where you are in the tutorial or how much time it takes.

Maybe there could be an unobtrusive progress bar or an indicator (Lesson 1 of 1337) showing you how you're moving through the tutorial?

**Comment by jacobswain** [comment]
That's a good point.  I'll add an indicator showing the user's progress.

**Comment by jacobswain** [comment]
Progress bar added.  It shows the current lesson and has dots to show which lessons you've completed.   The dots are also hyperlinks to the various lessons. Feedback is welcome. 

![screenshot 2015-04-21 19 20 47](https://cloud.githubusercontent.com/assets/1879320/7265200/a3424f28-e85b-11e4-80ef-c9516160ac9a.png)
